FROM node:14-slim

WORKDIR /app

COPY ./backend/package.json ./backend/package-lock.json ./

RUN npm ci
RUN npm install -g @nestjs/cli
RUN apt-get update && apt-get install -y procps

COPY ./backend .

CMD ["npm", "run", "start:dev"]
