version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.backend.local
    container_name: nestjs_dev
    environment:
      TZ: "Asia/Tokyo"
    tty: true
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
  db:
    image: postgres:13.3
    container_name: postgres_dev
    tty: true
    ports:
      - 5432:5432
    env_file: .env.local
